"""delete lock files table

Revision ID: 524d39aa6fab
Revises: b627c3692ba2
Create Date: 2024-03-30 15:40:24.179234

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "524d39aa6fab"
down_revision = "b627c3692ba2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lock_files")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lock_files",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###
