"""Add files table

Revision ID: b627c3692ba2
Revises: 715bcbf0afe4
Create Date: 2024-03-25 08:37:21.703143

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b627c3692ba2"
down_revision = "715bcbf0afe4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("icon", sa.String(), nullable=False),
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column("locked", sa.Boolean(), default=False, nullable=False),
        sa.Column("realname", sa.String(), nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("lapse_count", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_files_name"), ["name"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_files_realname"), ["realname"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_files_realname"))
        batch_op.drop_index(batch_op.f("ix_files_name"))

    op.drop_table("files")
    # ### end Alembic commands ###
